unit SimpleMigration;

interface

uses
  System.TypInfo,
  SimpleTypes, SimpleInterface;

type
  TSimpleMigration = class
  private
    class function MapFieldType(aTypeKind: TTypeKind; aHasFormat: Boolean;
      aMaxSize, aPrecision: Integer; aSQLType: TSQLType;
      aIsAutoInc: Boolean): String;
  public
    class function GenerateCreateTable<T: class, constructor>(aSQLType: TSQLType): String;
    class function GenerateDropTable<T: class, constructor>: String;
    class procedure CreateTable<T: class, constructor>(aQuery: iSimpleQuery);
    class procedure DropTable<T: class, constructor>(aQuery: iSimpleQuery);
  end;

implementation

uses
  System.Rtti, System.SysUtils,
  SimpleAttributes, SimpleRTTIHelper;

class function TSimpleMigration.GenerateCreateTable<T>(aSQLType: TSQLType): String;
var
  LCtx: TRttiContext;
  LType: TRttiType;
  LProp: TRttiProperty;
  LTableName, LFields, LFieldDef: String;
  LFormat: SimpleAttributes.Format;
  LMaxSize, LPrecision: Integer;
begin
  LCtx := TRttiContext.Create;
  try
    LType := LCtx.GetType(TypeInfo(T));

    if not LType.IsTabela then
      raise Exception.Create('Entity must have [Tabela] attribute');

    LTableName := LType.GetAttribute<Tabela>.Name;
    LFields := '';

    for LProp in LType.GetProperties do
    begin
      if LProp.IsIgnore then
        Continue;

      if not LProp.EhCampo then
        Continue;

      LFormat := LProp.GetAttribute<SimpleAttributes.Format>;
      LMaxSize := 0;
      LPrecision := 0;
      if Assigned(LFormat) then
      begin
        LMaxSize := LFormat.MaxSize;
        LPrecision := LFormat.Precision;
      end;

      LFieldDef := LProp.FieldName + ' ' +
        MapFieldType(LProp.PropertyType.TypeKind,
          Assigned(LFormat), LMaxSize, LPrecision,
          aSQLType, LProp.IsAutoInc);

      if LProp.EhChavePrimaria and not LProp.IsAutoInc then
        LFieldDef := LFieldDef + ' PRIMARY KEY';

      if LProp.IsNotNull and not LProp.IsAutoInc then
        LFieldDef := LFieldDef + ' NOT NULL';

      if LFields <> '' then
        LFields := LFields + ',' + sLineBreak + '  ';
      LFields := LFields + LFieldDef;
    end;

    Result := 'CREATE TABLE IF NOT EXISTS ' + LTableName + ' (' + sLineBreak +
      '  ' + LFields + sLineBreak + ')';
  finally
    LCtx.Free;
  end;
end;

class function TSimpleMigration.MapFieldType(aTypeKind: TTypeKind;
  aHasFormat: Boolean; aMaxSize, aPrecision: Integer;
  aSQLType: TSQLType; aIsAutoInc: Boolean): String;
begin
  if aIsAutoInc then
  begin
    case aSQLType of
      TSQLType.Firebird: Exit('INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
      TSQLType.MySQL:    Exit('INTEGER AUTO_INCREMENT PRIMARY KEY');
      TSQLType.SQLite:   Exit('INTEGER PRIMARY KEY AUTOINCREMENT');
      TSQLType.Oracle:   Exit('NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    else
      Exit('SERIAL PRIMARY KEY');
    end;
  end;

  case aTypeKind of
    tkInteger: Result := 'INTEGER';
    tkInt64: Result := 'BIGINT';
    tkFloat:
    begin
      if aHasFormat and (aPrecision > 0) then
        Result := System.SysUtils.Format('NUMERIC(%d,%d)', [aMaxSize, aPrecision])
      else
        Result := 'DOUBLE PRECISION';
    end;
    tkString, tkWChar, tkLString, tkWString, tkUString:
    begin
      if aHasFormat and (aMaxSize > 0) then
        Result := System.SysUtils.Format('VARCHAR(%d)', [aMaxSize])
      else
        Result := 'VARCHAR(255)';
    end;
    tkEnumeration: Result := 'INTEGER';
  else
    Result := 'VARCHAR(255)';
  end;
end;

class function TSimpleMigration.GenerateDropTable<T>: String;
var
  LCtx: TRttiContext;
  LType: TRttiType;
begin
  LCtx := TRttiContext.Create;
  try
    LType := LCtx.GetType(TypeInfo(T));

    if not LType.IsTabela then
      raise Exception.Create('Entity must have [Tabela] attribute');

    Result := 'DROP TABLE IF EXISTS ' + LType.GetAttribute<Tabela>.Name;
  finally
    LCtx.Free;
  end;
end;

class procedure TSimpleMigration.CreateTable<T>(aQuery: iSimpleQuery);
begin
  aQuery.SQL.Clear;
  aQuery.SQL.Add(GenerateCreateTable<T>(aQuery.SQLType));
  aQuery.ExecSQL;
end;

class procedure TSimpleMigration.DropTable<T>(aQuery: iSimpleQuery);
begin
  aQuery.SQL.Clear;
  aQuery.SQL.Add(GenerateDropTable<T>);
  aQuery.ExecSQL;
end;

end.
